name: app_3a_02
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  share_plus: ^11.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
   
  assets:
     - assets/images/mydiary.png
     - assets/images/profil.png
     - assets/images/logo.png
     - assets/images/leaf_bottom.png

  fonts:
     - family: IrishGrover
       fonts:
         - asset: assets/fonts/IrishGrover-Regular.ttf
           weight: 700
     - family: FrankRuhlLibre
       fonts:
         - asset: assets/fonts/FrankRuhlLibre-Regular.ttf
         - asset: assets/fonts/FrankRuhlLibre-Black.ttf
         - asset: assets/fonts/FrankRuhlLibre-Bold.ttf
         - asset: assets/fonts/FrankRuhlLibre-Light.ttf
         - asset: assets/fonts/FrankRuhlLibre-Medium.ttf
           weight: 700
      
   
