name: app_3a_02
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
   
  assets:
     - assets/images/mydiary.png
     - assets/images/profil.png
     - assets/images/logo.png

  fonts:
     - family: IrishGrover
       fonts:
         - asset: assets/fonts/IrishGrover-Regular.ttf
           weight: 700
     - family: FrankRuhlLibre
       fonts:
         - asset: assets/fonts/FrankRuhlLibre-Regular.ttf
         - asset: assets/fonts/FrankRuhlLibre-Black.ttf
         - asset: assets/fonts/FrankRuhlLibre-Bold.ttf
         - asset: assets/fonts/FrankRuhlLibre-Light.ttf
         - asset: assets/fonts/FrankRuhlLibre-Medium.ttf
           weight: 700
      
   
